# @package _global_
model:
  input_size: 
    height: 512
    width: 512
  output_size:
    height: 512
    width: 512
  n_heads : 1
  clip_grad_norm: true
  num_classes: ${data.num_classes}
  base_name: efficientnetv2
  model_name: tf_${model.base_name}_l_in21ft1k #m_in21ft1k
  backbone:
    class_name:
    params:
      weight_path: models/pretrained_models/efficientnet/