# @package _global_
albumentations:
  train:
    augs:
    - class_name: albumentations.OneOf
      p: 0.9
      params:
        - class_name: albumentations.HueSaturationValue
          params:
            always_apply: false
            hue_shift_limit:
            - -0.2
            - 0.2
            p: 0.9
            sat_shift_limit: 
            - -0.2
            - 0.2
            val_shift_limit: 
            - -0.2
            - 0.2
        - class_name: albumentations.RandomBrightnessContrast
          params:
            always_apply: false
            brightness_by_max: true
            brightness_limit:
            - -0.2
            - 0.2
            contrast_limit:
            - -0.2
            - 0.2
            p: 0.9
    - class_name: albumentations.Resize
      params:
        always_apply: false
        height: ${model.input_size}
        interpolation: 1
        width: ${model.input_size}
        p: 1
    - class_name: albumentations.ToGray
      params:
        always_apply: false
        p: 0.01
    - class_name: albumentations.HorizontalFlip
      params:
        always_apply: false
        p: 0.5
    - class_name: albumentations.VerticalFlip
      params:
        always_apply: false
        p: 0.5
    - class_name: albumentations.Cutout
      params: 
        always_apply: false
        num_holes: 6
        max_h_size: 44
        max_w_size: 44
        fill_value: 0
        p: 0.5
    - class_name: albumentations.pytorch.transforms.ToTensorV2
      params:
        always_apply: true
        p: 1.0
    bbox_params:
      _target_: albumentations.core.composition.BboxParams
      format: pascal_voc
      label_fields:
        - labels

  valid:
    augs:
    - class_name: albumentations.Resize
      params:
        always_apply: false
        height: ${model.input_size}
        interpolation: 1
        width: ${model.input_size}
        p: 1
    - class_name: albumentations.pytorch.transforms.ToTensorV2
      params:
        always_apply: true
        p: 1.0
    bbox_params:
      _target_: albumentations.core.composition.BboxParams
      format: pascal_voc
      label_fields:
        - labels

  test:
    augs:
      - class_name: albumentations.Resize
        params:
          always_apply: false
          height: ${model.input_size}
          interpolation: 1
          width: ${model.input_size}
          p: 1
      - class_name: albumentations.pytorch.transforms.ToTensorV2
        params:
          always_apply: true
          p: 1.0
    bbox_params:
      _target_: albumentations.core.composition.BboxParams
      format: pascal_voc
      label_fields:
        - labels