# @package _global_
defaults:
  - data: classification
  - test: classification
  - system: system

framework: pytorch
task: classification
model_path: models/model_id/20201013_13_17_10
test_id: test
  
hydra:
  run:
    dir: ${model_path}/result/${test_id} #${now:%Y%m%d_%H_%M_%S}
  sweep:
    dir: ${model_path}/result/
    subdir: ${test_id} #${now:%Y%m%d_%H_%M_%S}
